# Generated by Django 4.2.10 on 2024-03-27 12:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('route_datetime_create', models.DateTimeField(default=datetime.datetime.now)),
                ('desirable_price', models.FloatField(blank=True, null=True)),
                ('route_datetime', models.DateTimeField()),
                ('dep_lng', models.FloatField(blank=True, null=True)),
                ('dep_lat', models.FloatField(blank=True, null=True)),
                ('dst_lng', models.FloatField(blank=True, null=True)),
                ('dst_lat', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'active'), (0, 'inactive')])),
                ('fk_route', models.ForeignKey(db_column='fk_route', on_delete=django.db.models.deletion.CASCADE, to='route.route')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_order', models.CharField(default='пешеход', max_length=15)),
                ('fk_route_status', models.ForeignKey(db_column='fk_route_status', on_delete=django.db.models.deletion.CASCADE, to='route.routestatus')),
                ('fk_user', models.ForeignKey(db_column='fk_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
